---
- hosts: all
  tasks:
    - name: test connection
      become: yes
      become_user: root
      ping:
      register: message
    - name: print debug message
      debug:
        msg: "{{ message }}"
