apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-migrate2
  namespace: awx2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cephrbd
  resources:
    requests:
      storage: 5Gi